version: "3.10"

services:
  api:
    build: ./
    image: api-image
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
        - app.docker

  frontend:
    build: frontend
    image: frontend-image
    ports:
      - 3000:3000
    networks:
      AIservice:
        aliases:
        - frontend.docker
    depends_on:
      - api

networks:
  AIservice:
    external: true
